### PR TITLE
Migrating to build system. 

### PR DESCRIPTION
**Pull request by graymalkin**

### CODE REVIEW

**Comment by Tatskaari** [comment]
That is the worst pull request ever.

**Comment by graymalkin** [comment]
No shit. I left out the bit where I was gonna say that this is a slightly flakey change, too. It's a bitch to build this under windows. (by bitch, I mean near impossible)

**Comment by Tatskaari** [comment]
You suck. Get off my planet.

**Comment by graymalkin** [comment]
On the plus side, I did break it up into sane commits. It's just a really big pull. 

I'm gonna try and implement #weather and some sort of URL title retriever (as Noel is gone from #cs now).

#stats might also be quite fun, if I can print out things from the Erlang VM Stats

and then I'll make it so that Earl adds people with channel mode @ or + to admins, so chan admins can tell him to fuck off, if need be.

**Comment by Tatskaari** [comment]
Ben Basson 17:07: +To build, do `make --ignore-errors` (this is a work
around, some day I'll fix it)
                                I'm not sure ignoring errors is the same as
working

**Comment by graymalkin** [comment]
Totally is. I'm an Ostrich. This is my religion.

**Comment by graymalkin** [comment]
AACTUALLY... I'm gonna close this pull request. On further inspection this is more broken than I would like. I'll get back to you later.

**Comment by Tatskaari** [comment]
I don't see any sane commits...

**Comment by graymalkin** [comment]
There are 15.

**Comment by graymalkin** [comment]
Right, fixed.

**Pull request merged**
